# Default values for barotrauma.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: goldfish92/barotrauma-dedicated-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

server:
  containerEnv:
    #Name of server in server browser
    BAR_NAME: "GAME_NAME"
    #Password for server
    BAR_PASSWORD: "CHANGEME!"
    #List of users with permissions
    BAR_PERMISSIONS: "InGameUsername:Steam64ID:preset,"
resources:
  requests:
    memory: 12G
    cpu: 4

strategyType: RollingUpdate

service:
  type: ClusterIP

persistence:
  dataDir:
    enabled: false
    Size: 10Gi

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

nodeSelector: {}

tolerations: []

affinity: {}
