apiVersion: v1
kind: Service
metadata:
  name: {{ include "barotrauma.fullname" . }}
  labels:
    {{- include "barotrauma.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 27015
      targetPort: "barotrauma-27105"
      protocol: UDP
      name: "barotrauma-27015"
    - port: 27016
      targetPort: "barotrauma-27016"
      protocol: UDP
      name: "barotrauma-27016"
  selector:
    {{- include "barotrauma.selectorLabels" . | nindent 4 }}
